Resources:
  - TargetService:
      Type: AWS::ECS::Service
      Properties:
        TaskDefinition: "<TASK_DEFINITION>"
        LoadBalancerInfo:
          ContainerName: "loadTestMockTargetContainer"
          ContainerPort: 5000 
# Optional properties
        PlatformVersion: "LATEST"
        #NetworkConfiguration:
        #   AwsvpcConfiguration:
        #     Subnets: ["subnet-name-1", "subnet-name-2"]
        #     SecurityGroups: ["security-group"]
        #     AssignPublicIp: "ENABLED"

